In [26]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from tensorflow.keras import layers

In [27]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,0, 1, 0, 1, 0, 0, 1, 1]
})

In [28]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [29]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [30]:
X = df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y = df["needs_water"]

In [31]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_Scaler = scaler.fit_transform(X)
X_Scaler = pd.DataFrame(X_Scaler,columns=['soil_moisture', 'temperature_c', 'sunlight_hours'])
X_Scaler

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X_Scaler, y, test_size=0.25, random_state=42,stratify=y)

In [ ]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation="relu"),
    layers.Dense(1,activation="sigmoid")
])

In [ ]:
model.compile(optimizer="sgd",loss="binary_crossentropy",metrics=["accuracy"])
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 8)              │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 41 (164.00 B)

 Trainable params: 41 (164.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(
    X_train.values,y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,batch_size = 4,
    verbose = 1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 108ms/step - accuracy: 0.5000 - loss: 0.7075 - val_accuracy: 0.5000 - val_loss: 0.7268
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7062 - val_accuracy: 0.5000 - val_loss: 0.7250
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.7040 - val_accuracy: 0.5000 - val_loss: 0.7233
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.7017 - val_accuracy: 0.5000 - val_loss: 0.7217
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6992 - val_accuracy: 0.5000 - val_loss: 0.7201
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - accuracy: 0.5000 - loss: 0.6974 - val_accuracy: 0.5000 - val_loss: 0.7185
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6964 - val_accuracy: 0.5000 - val_loss: 0.7168
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6971 - val_accuracy: 0.5000 - val_loss: 0.7154
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6921 - val_accuracy: 0.5000 - val_loss: 0.7141
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.6913 - val_accuracy: 0.7500 - val_loss: 0.7128
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.5000 - loss: 0.6894 - val_accuracy: 0.7500 - val_loss: 0.7116
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6884 - val_accuracy: 0.7500 - val_loss: 0.7104
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6867 - val_accuracy: 0.7500 - val_loss: 0.7093
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6854 - val_accuracy: 0.7500 - val_loss: 0.7083
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6837 - val_accuracy: 0.7500 - val_loss: 0.7073
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6826 - val_accuracy: 0.7500 - val_loss: 0.7063
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.5000 - loss: 0.6809 - val_accuracy: 0.7500 - val_loss: 0.7053
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6791 - val_accuracy: 0.7500 - val_loss: 0.7044
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.5000 - loss: 0.6778 - val_accuracy: 0.7500 - val_loss: 0.7034
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6771 - val_accuracy: 0.7500 - val_loss: 0.7025
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.6764 - val_accuracy: 0.7500 - val_loss: 0.7015
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.6748 - val_accuracy: 0.7500 - val_loss: 0.7006
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6730 - val_accuracy: 0.7500 - val_loss: 0.6998
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.5000 - loss: 0.6726 - val_accuracy: 0.7500 - val_loss: 0.6989
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5833 - loss: 0.6714 - val_accuracy: 0.7500 - val_loss: 0.6981
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.5833 - loss: 0.6709 - val_accuracy: 0.7500 - val_loss: 0.6972
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6695 - val_accuracy: 0.7500 - val_loss: 0.6964
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6699 - val_accuracy: 0.5000 - val_loss: 0.6955
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 0.6672 - val_accuracy: 0.5000 - val_loss: 0.6947
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6664 - val_accuracy: 0.5000 - val_loss: 0.6940
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5000 - loss: 0.6648 - val_accuracy: 0.5000 - val_loss: 0.6933
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.6639 - val_accuracy: 0.5000 - val_loss: 0.6925
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6637 - val_accuracy: 0.5000 - val_loss: 0.6918
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6630 - val_accuracy: 0.5000 - val_loss: 0.6911
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6611 - val_accuracy: 0.5000 - val_loss: 0.6904
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6610 - val_accuracy: 0.5000 - val_loss: 0.6898
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.6600 - val_accuracy: 0.5000 - val_loss: 0.6891
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss: 0.6586 - val_accuracy: 0.5000 - val_loss: 0.6884
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6585 - val_accuracy: 0.5000 - val_loss: 0.6878
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6574 - val_accuracy: 0.5000 - val_loss: 0.6871
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6560 - val_accuracy: 0.5000 - val_loss: 0.6865
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6571 - val_accuracy: 0.5000 - val_loss: 0.6858
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.6544 - val_accuracy: 0.5000 - val_loss: 0.6852
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5833 - loss: 0.6543 - val_accuracy: 0.5000 - val_loss: 0.6846
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.6538 - val_accuracy: 0.5000 - val_loss: 0.6840
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5833 - loss: 0.6520 - val_accuracy: 0.5000 - val_loss: 0.6834
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5833 - loss: 0.6522 - val_accuracy: 0.5000 - val_loss: 0.6827
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5833 - loss: 0.6503 - val_accuracy: 0.5000 - val_loss: 0.6821
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.5833 - loss: 0.6517 - val_accuracy: 0.5000 - val_loss: 0.6815
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6507 - val_accuracy: 0.5000 - val_loss: 0.6809
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6479 - val_accuracy: 0.5000 - val_loss: 0.6803
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.6478 - val_accuracy: 0.5000 - val_loss: 0.6797
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6475 - val_accuracy: 0.5000 - val_loss: 0.6791
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6459 - val_accuracy: 0.5000 - val_loss: 0.6786
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6454 - val_accuracy: 0.5000 - val_loss: 0.6780
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6447 - val_accuracy: 0.5000 - val_loss: 0.6774
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6460 - val_accuracy: 0.5000 - val_loss: 0.6768
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6429 - val_accuracy: 0.5000 - val_loss: 0.6762
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6435 - val_accuracy: 0.5000 - val_loss: 0.6757
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6415 - val_accuracy: 0.5000 - val_loss: 0.6751
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.6667 - loss: 0.6406 - val_accuracy: 0.5000 - val_loss: 0.6745
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6667 - loss: 0.6401 - val_accuracy: 0.5000 - val_loss: 0.6739
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6387 - val_accuracy: 0.5000 - val_loss: 0.6734
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6667 - loss: 0.6386 - val_accuracy: 0.5000 - val_loss: 0.6728
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6376 - val_accuracy: 0.5000 - val_loss: 0.6722
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6364 - val_accuracy: 0.5000 - val_loss: 0.6717
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6380 - val_accuracy: 0.5000 - val_loss: 0.6711
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.6667 - loss: 0.6356 - val_accuracy: 0.5000 - val_loss: 0.6706
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6361 - val_accuracy: 0.5000 - val_loss: 0.6700
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6667 - loss: 0.6355 - val_accuracy: 0.5000 - val_loss: 0.6695
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6329 - val_accuracy: 0.5000 - val_loss: 0.6689
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6321 - val_accuracy: 0.5000 - val_loss: 0.6684
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6313 - val_accuracy: 0.5000 - val_loss: 0.6678
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6306 - val_accuracy: 0.5000 - val_loss: 0.6673
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.6309 - val_accuracy: 0.5000 - val_loss: 0.6667
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.6667 - loss: 0.6297 - val_accuracy: 0.5000 - val_loss: 0.6662
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - accuracy: 0.6667 - loss: 0.6289 - val_accuracy: 0.5000 - val_loss: 0.6656
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6667 - loss: 0.6283 - val_accuracy: 0.5000 - val_loss: 0.6651
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6276 - val_accuracy: 0.5000 - val_loss: 0.6645
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6667 - loss: 0.6272 - val_accuracy: 0.5000 - val_loss: 0.6640
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6260 - val_accuracy: 0.7500 - val_loss: 0.6634
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6253 - val_accuracy: 0.7500 - val_loss: 0.6629
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6245 - val_accuracy: 0.7500 - val_loss: 0.6623
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.6238 - val_accuracy: 0.7500 - val_loss: 0.6618
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6232 - val_accuracy: 0.7500 - val_loss: 0.6612
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6223 - val_accuracy: 0.7500 - val_loss: 0.6607
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6236 - val_accuracy: 0.7500 - val_loss: 0.6601
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6211 - val_accuracy: 0.7500 - val_loss: 0.6596
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.6196 - val_accuracy: 0.7500 - val_loss: 0.6590
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6667 - loss: 0.6199 - val_accuracy: 0.7500 - val_loss: 0.6585
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6182 - val_accuracy: 0.7500 - val_loss: 0.6580
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6667 - loss: 0.6182 - val_accuracy: 0.7500 - val_loss: 0.6574
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.6667 - loss: 0.6172 - val_accuracy: 0.7500 - val_loss: 0.6569
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6667 - loss: 0.6167 - val_accuracy: 0.7500 - val_loss: 0.6564
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6667 - loss: 0.6159 - val_accuracy: 0.7500 - val_loss: 0.6559
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.6157 - val_accuracy: 0.7500 - val_loss: 0.6554
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6158 - val_accuracy: 0.7500 - val_loss: 0.6549
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6132 - val_accuracy: 0.7500 - val_loss: 0.6544
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6667 - loss: 0.6129 - val_accuracy: 0.7500 - val_loss: 0.6539
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6125 - val_accuracy: 0.7500 - val_loss: 0.6534