In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from tensorflow import keras 
from tensorflow.keras import layers

In [14]:
df = pd.DataFrame({
    "soil_moisture": [0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30],
    "temperature_c": [34, 30, 26, 22, 28, 30, 19, 22,35, 24, 33, 33, 21, 25, 20, 29],
    "sunlight_hours": [9, 8, 7, 4, 8, 10, 3, 10,12, 5, 9, 11, 2, 6, 1, 9],
    "needs_water": [1, 1, 1, 0, 0, 0, 0, 1,0, 1, 0, 1, 0, 0, 1, 1]
})
df.head()

   soil_moisture  temperature_c  sunlight_hours  needs_water
0           0.10             34               9            1
1           0.15             30               8            1
2           0.20             26               7            1
3           0.25             22               4            0
4           0.40             28               8            0

In [15]:
X = df.drop("needs_water",axis=1)
y = df["needs_water"]

In [16]:
X.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours'], dtype='object')

In [17]:
scaler = MinMaxScaler()
col = ['soil_moisture', 'temperature_c', 'sunlight_hours']
X[col] = scaler.fit_transform(X)
X.head()

   soil_moisture  temperature_c  sunlight_hours
0       0.066667         0.9375        0.727273
1       0.133333         0.6875        0.636364
2       0.200000         0.4375        0.545455
3       0.266667         0.1875        0.272727
4       0.466667         0.5625        0.636364

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42,stratify=y)

In [19]:
model = keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(8,activation="relu"),
    layers.Dense(1,activation="sigmoid")
])
model

In [20]:
model.compile(optimizer="sgd",loss="binary_crossentropy",metrics=["accuracy"])

In [24]:
his = model.fit(
    X_train.values,
    y_train.values,
    validation_data = (X_test.values,y_test.values),
    epochs = 100,
    batch_size = 4,
    verbose = 1, 
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.9167 - loss: 0.6445 - val_accuracy: 0.7500 - val_loss: 0.6830
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6426 - val_accuracy: 0.7500 - val_loss: 0.6827
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.6421 - val_accuracy: 0.7500 - val_loss: 0.6823
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6420 - val_accuracy: 0.7500 - val_loss: 0.6819
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.6417 - val_accuracy: 0.7500 - val_loss: 0.6816
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6410 - val_accuracy: 0.7500 - val_loss: 0.6812
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6407 - val_accuracy: 0.7500 - val_loss: 0.6808
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6402 - val_accuracy: 0.7500 - val_loss: 0.6805
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.6397 - val_accuracy: 0.7500 - val_loss: 0.6801
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9167 - loss: 0.6401 - val_accuracy: 0.7500 - val_loss: 0.6797
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.9167 - loss: 0.6383 - val_accuracy: 0.7500 - val_loss: 0.6793
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.6383 - val_accuracy: 0.7500 - val_loss: 0.6790
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.6374 - val_accuracy: 0.7500 - val_loss: 0.6786
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.6374 - val_accuracy: 0.7500 - val_loss: 0.6782
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6368 - val_accuracy: 0.7500 - val_loss: 0.6778
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.9167 - loss: 0.6359 - val_accuracy: 0.7500 - val_loss: 0.6774
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.6354 - val_accuracy: 0.7500 - val_loss: 0.6771
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6366 - val_accuracy: 0.7500 - val_loss: 0.6767
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.6349 - val_accuracy: 0.7500 - val_loss: 0.6763
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6344 - val_accuracy: 0.7500 - val_loss: 0.6759
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6339 - val_accuracy: 0.7500 - val_loss: 0.6755
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.9167 - loss: 0.6333 - val_accuracy: 0.7500 - val_loss: 0.6752
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.6331 - val_accuracy: 0.7500 - val_loss: 0.6748
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9167 - loss: 0.6321 - val_accuracy: 0.7500 - val_loss: 0.6744
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.6318 - val_accuracy: 0.7500 - val_loss: 0.6740
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6330 - val_accuracy: 0.7500 - val_loss: 0.6736
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6310 - val_accuracy: 0.7500 - val_loss: 0.6732
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6313 - val_accuracy: 0.7500 - val_loss: 0.6728
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.6296 - val_accuracy: 0.7500 - val_loss: 0.6724
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6294 - val_accuracy: 0.7500 - val_loss: 0.6720
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6291 - val_accuracy: 0.7500 - val_loss: 0.6717
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6293 - val_accuracy: 0.7500 - val_loss: 0.6713
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6280 - val_accuracy: 0.7500 - val_loss: 0.6709
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6275 - val_accuracy: 0.7500 - val_loss: 0.6705
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6266 - val_accuracy: 0.7500 - val_loss: 0.6701
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.6265 - val_accuracy: 0.7500 - val_loss: 0.6697
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6261 - val_accuracy: 0.7500 - val_loss: 0.6692
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.6254 - val_accuracy: 0.7500 - val_loss: 0.6688
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6246 - val_accuracy: 0.7500 - val_loss: 0.6683
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6244 - val_accuracy: 0.7500 - val_loss: 0.6679
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.6236 - val_accuracy: 0.7500 - val_loss: 0.6674
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6235 - val_accuracy: 0.7500 - val_loss: 0.6669
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6226 - val_accuracy: 0.7500 - val_loss: 0.6665
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6224 - val_accuracy: 0.7500 - val_loss: 0.6660
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6218 - val_accuracy: 0.7500 - val_loss: 0.6655
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6218 - val_accuracy: 0.7500 - val_loss: 0.6650
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6205 - val_accuracy: 0.7500 - val_loss: 0.6645
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.6207 - val_accuracy: 0.7500 - val_loss: 0.6640
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.9167 - loss: 0.6195 - val_accuracy: 0.7500 - val_loss: 0.6634
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.6207 - val_accuracy: 0.7500 - val_loss: 0.6629
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6204 - val_accuracy: 0.7500 - val_loss: 0.6624
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6179 - val_accuracy: 0.7500 - val_loss: 0.6619
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.9167 - loss: 0.6191 - val_accuracy: 0.7500 - val_loss: 0.6614
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.6169 - val_accuracy: 0.7500 - val_loss: 0.6608
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.6167 - val_accuracy: 0.7500 - val_loss: 0.6603
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6164 - val_accuracy: 0.7500 - val_loss: 0.6598
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.6157 - val_accuracy: 0.7500 - val_loss: 0.6594
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.6161 - val_accuracy: 0.7500 - val_loss: 0.6589
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.6148 - val_accuracy: 0.7500 - val_loss: 0.6584
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6139 - val_accuracy: 0.7500 - val_loss: 0.6579
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.6139 - val_accuracy: 0.7500 - val_loss: 0.6574
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.9167 - loss: 0.6129 - val_accuracy: 0.7500 - val_loss: 0.6569
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6141 - val_accuracy: 0.7500 - val_loss: 0.6564
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9167 - loss: 0.6119 - val_accuracy: 0.7500 - val_loss: 0.6559
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6117 - val_accuracy: 0.7500 - val_loss: 0.6554
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.9167 - loss: 0.6113 - val_accuracy: 0.7500 - val_loss: 0.6549
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.9167 - loss: 0.6103 - val_accuracy: 0.7500 - val_loss: 0.6544
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.6102 - val_accuracy: 0.7500 - val_loss: 0.6539
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6093 - val_accuracy: 0.7500 - val_loss: 0.6534
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 1.0000 - loss: 0.6102 - val_accuracy: 0.7500 - val_loss: 0.6529
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.6088 - val_accuracy: 0.7500 - val_loss: 0.6524
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.9167 - loss: 0.6078 - val_accuracy: 0.7500 - val_loss: 0.6519
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.6076 - val_accuracy: 0.7500 - val_loss: 0.6514
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.6073 - val_accuracy: 0.7500 - val_loss: 0.6509
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.9167 - loss: 0.6069 - val_accuracy: 0.7500 - val_loss: 0.6504
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.6057 - val_accuracy: 0.7500 - val_loss: 0.6499
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 1.0000 - loss: 0.6051 - val_accuracy: 0.7500 - val_loss: 0.6494
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6052 - val_accuracy: 0.7500 - val_loss: 0.6488
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.6045 - val_accuracy: 0.7500 - val_loss: 0.6483
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 1.0000 - loss: 0.6036 - val_accuracy: 0.7500 - val_loss: 0.6478
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.6034 - val_accuracy: 0.7500 - val_loss: 0.6473
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.9167 - loss: 0.6042 - val_accuracy: 0.7500 - val_loss: 0.6467
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.6023 - val_accuracy: 0.7500 - val_loss: 0.6462
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 1.0000 - loss: 0.6014 - val_accuracy: 0.7500 - val_loss: 0.6457
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.6014 - val_accuracy: 0.7500 - val_loss: 0.6451
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.6023 - val_accuracy: 0.7500 - val_loss: 0.6446
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.9167 - loss: 0.6003 - val_accuracy: 0.7500 - val_loss: 0.6441
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9167 - loss: 0.5998 - val_accuracy: 0.7500 - val_loss: 0.6435
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 1.0000 - loss: 0.5994 - val_accuracy: 0.7500 - val_loss: 0.6430
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.9167 - loss: 0.5997 - val_accuracy: 0.7500 - val_loss: 0.6424
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 1.0000 - loss: 0.5990 - val_accuracy: 0.7500 - val_loss: 0.6419
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5979 - val_accuracy: 0.7500 - val_loss: 0.6413
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.5973 - val_accuracy: 0.7500 - val_loss: 0.6408
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5966 - val_accuracy: 0.7500 - val_loss: 0.6402
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 1.0000 - loss: 0.5977 - val_accuracy: 0.7500 - val_loss: 0.6397
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 1.0000 - loss: 0.5958 - val_accuracy: 0.7500 - val_loss: 0.6391
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 1.0000 - loss: 0.5953 - val_accuracy: 0.7500 - val_loss: 0.6385
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 1.0000 - loss: 0.5945 - val_accuracy: 0.7500 - val_loss: 0.6380
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 1.0000 - loss: 0.5953 - val_accuracy: 0.7500 - val_loss: 0.6374
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 1.0000 - loss: 0.5938 - val_accuracy: 0.7500 - val_loss: 0.6369

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()